### ISSUE TITLE
It won't load errors!

### ISSUE THREAD

**Issue by Baavoz** [NiklasBorglund/AssetBundleCreator#2]
when i put those files to assets folder in my project i won't load errors. Do i have something wrong with unity or what? iam using unity 5.1.1f1

**Comment by NiklasBorglund** [comment]
AssetBundleCreator was created for Unity 4.X and is not developed on any longer. It does not support Unity 5.

However, there are some people that made it work for Unity 5. Maybe that can work - https://www.youtube.com/watch?v=URZBRnHCa7U

**Comment by Baavoz** [comment]
Okay my assets bundle creator is working but when i press build assets
bundle button won't do anything?
